# Telegraf Configuration for Unknown Customer
[agent]
interval = "10s"
round_interval = true
metric_batch_size = 1000
metric_buffer_limit = 10000
flush_interval = "10s"
flush_jitter = "0s"

[[outputs.influxdb]]
urls = ["http://localhost:8086"]
database = "MFEC"
skip_database_creation = false
timeout = "5s"

# TOPIC_ID: TOP00002
[[inputs.mqtt_consumer]]
servers = ["tcp://undefined:undefined"]
topics = ["undefined"]
qos = 0
connection_timeout = "30s"
data_format = "json"
tag_keys = ["Sensor "]
name_override = "Sensor "
# TOPIC_ID: TOP00003
[[inputs.mqtt_consumer]]
servers = ["tcp://undefined:undefined"]
topics = ["undefined"]
qos = 0
connection_timeout = "30s"
data_format = "json"
tag_keys = ["MFEC_energyMeter003"]
name_override = "MFEC_energyMeter003"
# TOPIC_ID: 0003
[[inputs.mqtt_consumer]]
servers = ["tcp://undefined:undefined"]
topics = ["undefined"]
qos = 0
connection_timeout = "30s"
data_format = "json"
tag_keys = ["MFEC_energyMeter003"]
name_override = "MFEC_energyMeter003"
# TOPIC_ID: 00000004
[[inputs.mqtt_consumer]]
servers = ["tcp://undefined:undefined"]
topics = ["undefined"]
qos = 0
connection_timeout = "30s"
data_format = "json"
tag_keys = ["Sensor_Office_01"]
name_override = "Sensor_Office_01"
# TOPIC_ID: 00000002
[[inputs.mqtt_consumer]]
servers = ["tcp://undefined:undefined"]
topics = ["undefined"]
qos = 0
connection_timeout = "30s"
data_format = "json"
tag_keys = ["Sensor "]
name_override = "Sensor "
# TOPIC_ID: 00000001
[[inputs.mqtt_consumer]]
servers = ["tcp://undefined:undefined"]
topics = ["undefined"]
qos = 0
connection_timeout = "30s"
data_format = "json"
tag_keys = ["Sensor_Office_01"]
name_override = "Sensor_Office_01"
# TOPIC_ID: 00000003
[[inputs.mqtt_consumer]]
servers = ["tcp://undefined:undefined"]
topics = ["undefined"]
qos = 0
connection_timeout = "30s"
data_format = "json"
tag_keys = ["Sensor_Office_01"]
name_override = "Sensor_Office_01"