 # Telegraf Configuration File

[agent]
interval = "10s"
round_interval = true
metric_batch_size = 1000
metric_buffer_limit = 10000
flush_interval = "10s"
flush_jitter = "0s"

[[inputs.mqtt_consumer]]
servers = ["tcp://mqtt:1883"]
topics = ["sensor/cu_cisco"]
qos = 0
connection_timeout = "30s"
data_format = "json"
tag_keys = ["cu_cisco"]
name_override = "cu_cisco"

[[inputs.mqtt_consumer]]
servers = ["tcp://mqtt:1883"]
topics = ["sensor/cu_energymeter"]
qos = 0
connection_timeout = "30s"
data_format = "json"
tag_keys = ["cu_energymeter"]
name_override = "cu_energymeter"

[[outputs.influxdb]]
urls = ["http://influxdb:8086"]
database = "CUDB"
skip_database_creation = false
timeout = "5s"

